---
# External roles required for this project
- src: geerlingguy.postfix
  version: 1.7.0

- src: geerlingguy.dovecot
  version: 1.3.0

- src: geerlingguy.ssl-certs
  version: 1.2.0

- src: geerlingguy.firewall
  version: 2.7.0

- src: geerlingguy.mailhog
  version: 1.1.0
  # For testing email delivery in staging

- src: davidwittman.redis
  version: 1.2.1
  # For rate limiting and caching

# Collections
collections:
  - name: community.general
    version: 5.0.0
  
  - name: ansible.posix
    version: 1.3.0
  
  - name: community.crypto
    version: 2.0.0
