---
all:
  children:
    mail_servers:
      hosts:
        mail-stage-01:
          ansible_host: 192.168.2.10
          ansible_user: deploy
    
    smtp_relays:
      hosts:
        relay-stage-01:
          ansible_host: 192.168.2.20
          ansible_user: deploy
    
    monitoring:
      hosts:
        monitor-stage-01:
          ansible_host: 192.168.2.30
          ansible_user: deploy

    staging:
      children:
        mail_servers:
        smtp_relays:
        monitoring:
