---
all:
  children:
    mail_servers:
      hosts:
        mail-prod-01:
          ansible_host: 192.168.1.10
          ansible_user: deploy
        mail-prod-02:
          ansible_host: 192.168.1.11
          ansible_user: deploy
    
    smtp_relays:
      hosts:
        relay-prod-01:
          ansible_host: 192.168.1.20
          ansible_user: deploy
    
    monitoring:
      hosts:
        monitor-prod-01:
          ansible_host: 192.168.1.30
          ansible_user: deploy

    production:
      children:
        mail_servers:
        smtp_relays:
        monitoring:
